/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IWWk9cB37NS
 */
import { Tabs } from "@/app/components/ui/tabs";
import { AvatarImage, Avatar } from "@/app/components/ui/avatar";
import Link from "next/link";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/app/components/ui/card";
import { Button } from "@/app/components/ui/button";

export default function profile() {
  return (
    <div className="min-h-screen bg-gray-100 p-8">
      <header className="flex justify-between items-center mb-6">
        <Tabs>
          <div className="flex space-x-4">
            <div>Overview</div>
            <div>Schedule</div>
            <div>Highlights</div>
          </div>
        </Tabs>
        <Avatar>
          <AvatarImage
            alt="User avatar"
            src="/placeholder.svg?height=32&width=32"
          />
        </Avatar>
      </header>
      <div className="flex">
        <aside className="w-64 pr-8">
          <nav className="space-y-1">
            <Link className="block" href="#">
              <ArrowLeftIcon className="inline-block w-4 h-4 mr-2" />
              Account Settings{"\n                  "}
            </Link>
            <Link className="block pl-4 text-gray-700" href="#">
              Profile Information
            </Link>
            <Link className="block pl-4 text-gray-700" href="#">
              Payment Methods
            </Link>
            <Link className="block pl-4 text-gray-700" href="#">
              Security
            </Link>
            <Link className="block pl-4 text-gray-700" href="#">
              Event
            </Link>
            <Link className="block pl-4 text-gray-700" href="#">
              Notifications
            </Link>
            <Link className="block pl-4 text-gray-700" href="#">
              Add Attendees
            </Link>
            <Link className="block pl-4 text-gray-700" href="#">
              Log out
            </Link>
          </nav>
        </aside>
        <main className="flex-1">
          <div className="grid grid-cols-3 gap-8">
            <Card className="col-span-2">
              <CardHeader>
                <CardTitle>Profile Information</CardTitle>
                <CardDescription>Edit Profile Details</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center space-x-4">
                  <Avatar>
                    <AvatarImage
                      alt="Profile avatar"
                      src="/placeholder.svg?height=64&width=64"
                    />
                  </Avatar>
                  <div className="grid grid-cols-2 gap-x-4 gap-y-2">
                    <div className="font-medium">Full Name</div>
                    <div>John Doe</div>
                    <div className="font-medium">Location</div>
                    <div>New York, USA</div>
                    <div className="font-medium">Email</div>
                    <div>johndoe@email.com</div>
                    <div className="font-medium">Nationality</div>
                    <div>American</div>
                    <div className="font-medium">Date of Birth</div>
                    <div>01/01/1990</div>
                    <div className="col-span-2 flex justify-end space-x-2">
                      <Button variant="ghost">Edit</Button>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Exclusive</CardTitle>
              </CardHeader>
              <CardContent className="flex flex-col items-center justify-center space-y-4">
                <HandIcon className="w-12 h-12 text-gray-500" />
                <div className="text-center">
                  <CardDescription>
                    Do you want to receive exclusive offers and discounts for
                    upcoming events?
                  </CardDescription>
                  <p>Join our Event Club now!</p>
                </div>
                <Button>Join now</Button>
              </CardContent>
            </Card>
          </div>
        </main>
      </div>
    </div>
  );
}

function ArrowLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  );
}

function HandIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 11V6a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v0" />
      <path d="M14 10V4a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v2" />
      <path d="M10 10.5V6a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v8" />
      <path d="M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15" />
    </svg>
  );
}
