export const sidebarStyles = {
    Card: {
      width: '350px',
      height: '550px',
      backgroundColor: '#f0f0f0',
      position: 'relative',
    },
    Icon: {
      color: '#030303',
      fill: '#030303',
      width: '20px',
      height: '20px',
    },
    Text: {
      color: '#030303',
      fontSize: '14px',
      fontFamily: 'Poppins',
      fontWeight: 300,
      lineHeight: '22px',
      textAlign: 'right',
    },
    Button: {
      cursor: 'pointer',
      top: '554px',
      left: '64px',
      width: '310px',
      height: '42px',
      padding: '0px 8px',
      border: '0',
      boxSizing: 'border-box',
      borderRadius: '12px',
      backgroundColor: '#1b1b1d',
      color: '#ffffff',
      fontSize: '14px',
      fontFamily: 'Poppins',
      lineHeight: '18px',
      outline: 'none',
    },
  };